version: "3.8"

services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./modules/auth
    container_name: auth-service
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: authuser
      DB_PASSWORD: authpass
    ports:
      - "3000:3000"
    depends_on:
      - auth-db

  auth:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./modules/auth:/usr/src/app
    command: yarn dev
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/authdb
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  auth-db-data:
