version: "3"

services:
    saascript-mongo:
        container_name: saascript_mongo
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/saascript-mongo:/data/db

    saascript:
        container_name: saascript
        build: .
        image: saascript
        ports:
            - 8080:8080
        depends_on:
            - saascript-mongo
