version: "3"

services:
    saascript:
        environment:
            - DEBUG=1
        command: npm run debug
        volumes:
            - ./dist:/usr/app/saascript/dist
            - ./logs:/usr/app/saascript/logs

        ports:
            - "9229:9229"
